# Module 8 Lab 1 Exploring Dataset with Numpy


### NumPy is great at storing and manipulating numerical data in arrays.

#### Movie Reviewer is a fictional movie review site where six good friends watch and review movie, Micky, Donald, Goofy, Daisy, Minnie and Pluto watch movies and give them ratings on a scale of 0 to 100.

#### Step1: Import Numpy as np

In [1]:
import numpy as np

#### Step 2: Create a  1-dimensional array for the first movie they reviewed. Store in NumPy array movie_ratings
##### You can enter random numbers for each review between 0 - 100 
##### Hint: You can use Excel or np.random.randint(0, 100, size=(6,10))

In [4]:
a = np.random.randint(0, 100, size=(6,10))
print(a)
a[0,:]

[[92 24 18 56  2 43 36 93 96 73]
 [ 1 96 96 92 17  5 80 10 70 58]
 [66 61  6 18  2  5  0 72  2 61]
 [76 29 93 47 19 44 46 67 67 78]
 [45  1 83 54 85 32 52 46 36 68]
 [68 32 76 69 45 39 93 21 52 84]]


array([92, 24, 18, 56,  2, 43, 36, 93, 96, 73])

#### Step 3: The gang went to see 9 more movies. Create a  2-dimensional array where each row is their ratings for a specific movie.
##### You can enter random numbers for each review between 0 - 100

In [16]:
b = np.random.randint(0, 100, size=(6,9))
print(b)
c = np.hstack((a,b))
print(c)

[[64 69 38  2 80 65 29 85 31]
 [27 54 91 11 34 89 84 83 41]
 [19 80 79  9 37 18 59 23 74]
 [61 11 71 37 24 89 57 84 88]
 [24 66 47 48 72 49 16 10 12]
 [70 93 13 99 81 39 87 15 48]]
[[92 24 18 56  2 43 36 93 96 73 64 69 38  2 80 65 29 85 31]
 [ 1 96 96 92 17  5 80 10 70 58 27 54 91 11 34 89 84 83 41]
 [66 61  6 18  2  5  0 72  2 61 19 80 79  9 37 18 59 23 74]
 [76 29 93 47 19 44 46 67 67 78 61 11 71 37 24 89 57 84 88]
 [45  1 83 54 85 32 52 46 36 68 24 66 47 48 72 49 16 10 12]
 [68 32 76 69 45 39 93 21 52 84 70 93 13 99 81 39 87 15 48]]


#### Step 4: Some fans prefer to have the movies rated on a five star scale, so we can use NumPy to easily divide each element by 20.

In [19]:
star = c / 20
print(star)

[[4.6  1.2  0.9  2.8  0.1  2.15 1.8  4.65 4.8  3.65 3.2  3.45 1.9  0.1
  4.   3.25 1.45 4.25 1.55]
 [0.05 4.8  4.8  4.6  0.85 0.25 4.   0.5  3.5  2.9  1.35 2.7  4.55 0.55
  1.7  4.45 4.2  4.15 2.05]
 [3.3  3.05 0.3  0.9  0.1  0.25 0.   3.6  0.1  3.05 0.95 4.   3.95 0.45
  1.85 0.9  2.95 1.15 3.7 ]
 [3.8  1.45 4.65 2.35 0.95 2.2  2.3  3.35 3.35 3.9  3.05 0.55 3.55 1.85
  1.2  4.45 2.85 4.2  4.4 ]
 [2.25 0.05 4.15 2.7  4.25 1.6  2.6  2.3  1.8  3.4  1.2  3.3  2.35 2.4
  3.6  2.45 0.8  0.5  0.6 ]
 [3.4  1.6  3.8  3.45 2.25 1.95 4.65 1.05 2.6  4.2  3.5  4.65 0.65 4.95
  4.05 1.95 4.35 0.75 2.4 ]]


#### Step 5: Now let's say the ratings are always in the same order (Micky, Donald, Goofy, Daisy, Minnie, Pluto) if we wanted to create an array that only had Micky's ratings, we could select that from our movie_ratings array.

In [21]:
micky = star[0,:]
print(micky)

[4.6  1.2  0.9  2.8  0.1  2.15 1.8  4.65 4.8  3.65 3.2  3.45 1.9  0.1
 4.   3.25 1.45 4.25 1.55]


#### Step 6: Now, say we find that we have very similar taste to Pluto, so we only want to see movies that he gives a good rating to, we can use logic to select those movies.

In [22]:
pluto = star[5,:]
print(pluto)
pluto > 4

[3.4  1.6  3.8  3.45 2.25 1.95 4.65 1.05 2.6  4.2  3.5  4.65 0.65 4.95
 4.05 1.95 4.35 0.75 2.4 ]


array([False, False, False, False, False, False,  True, False, False,
        True, False,  True, False,  True,  True, False,  True, False,
       False])

#### Step 7: Calculate the average rating for the 7th movie reviewed.
##### Hint: Arrays start at 0 & use .mean of axis 0

In [25]:
calculatedMean = np.mean(star, axis = 0)
print(calculatedMean)
calculatedMean[6]


[2.9        2.025      3.1        2.8        1.41666667 1.4
 2.55833333 2.575      2.69166667 3.51666667 2.20833333 3.10833333
 2.825      1.71666667 2.73333333 2.90833333 2.76666667 2.5
 2.45      ]


2.558333333333333

#### Submit screenshots in Word or PDF  and .ipynb file Juypter Notebook